### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by q4a** [NuclearAPK/go-techLog1C#10]
Периодически собранная версия 5e24656148007b7bf88a99c7e6d7151ffff342e9 падает с ошибкой `fatal error: out of memory`.
Есть предположение, с чем это связано? Может какие-то настройки нужно подкрутить?

Полный текст ошибки:
```
runtime: VirtualAlloc of 5471715328 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0xd7978f?, 0xcc6ff30000?})
        C:/Program Files/Go/src/runtime/panic.go:1077 +0x65 fp=0x3d821ff918 sp=0x3d821ff8e8 pc=0x8d7385
runtime.sysUsedOS(0xcb6a122000, 0x14623c000)
        C:/Program Files/Go/src/runtime/mem_windows.go:83 +0x1bb fp=0x3d821ff978 sp=0x3d821ff918 pc=0x8b709b
runtime.sysUsed(...)
        C:/Program Files/Go/src/runtime/mem.go:77
runtime.(*mheap).allocSpan(0x107b960, 0xa311e, 0x0, 0x4b?)
        C:/Program Files/Go/src/runtime/mheap.go:1351 +0x487 fp=0x3d821ffa18 sp=0x3d821ff978 pc=0x8c8547
runtime.(*mheap).alloc.func1()
        C:/Program Files/Go/src/runtime/mheap.go:968 +0x5c fp=0x3d821ffa60 sp=0x3d821ffa18 pc=0x8c7cfc
runtime.systemstack()
        C:/Program Files/Go/src/runtime/asm_amd64.s:509 +0x49 fp=0x3d821ffa70 sp=0x3d821ffa60 pc=0x904e49

goroutine 15 [running]:
runtime.systemstack_switch()
        C:/Program Files/Go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc00061c548 sp=0xc00061c538 pc=0x904de8
runtime.(*mheap).alloc(0x14623c000?, 0xa311e?, 0xb8?)
        C:/Program Files/Go/src/runtime/mheap.go:962 +0x5b fp=0xc00061c590 sp=0xc00061c548 pc=0x8c7c5b
runtime.(*mcache).allocLarge(0x40?, 0x14623c000, 0x0?)
        C:/Program Files/Go/src/runtime/mcache.go:234 +0x85 fp=0xc00061c5d8 sp=0xc00061c590 pc=0x8b5f65
runtime.mallocgc(0x14623c000, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/malloc.go:1123 +0x4f6 fp=0xc00061c640 sp=0xc00061c5d8 pc=0x8ad396
runtime.growslice(0xc91f050000, 0xc0002ed700?, 0x40?, 0x40?, 0xc000018070?)
        C:/Program Files/Go/src/runtime/slice.go:266 +0x4cf fp=0xc00061c6b0 sp=0xc00061c640 pc=0x8ebe2f
main.readFile({{0xc00018c2a0, 0x3d}, 0x11862e327, 0x0, {0xc00018c2d1, 0x8}, {0x10788bf0, 0xedca2701b, 0x10654e0}, {0xc00018c2c5, ...}, ...})
        C:/soft/go-techLog1C-main/main.go:274 +0x16a fp=0xc00061c720 sp=0xc00061c6b0 pc=0xc7c80a
main.jobExtractTechLogs({0xc0009de000, 0x9a9, 0xb62?}, 0x2, 0xc00012c000, 0xc00004e7e0?)
        C:/soft/go-techLog1C-main/main.go:383 +0x398 fp=0xc00061dfa0 sp=0xc00061c720 pc=0xc7d6d8
main.main.func7()
        C:/soft/go-techLog1C-main/main.go:817 +0x34 fp=0xc00061dfe0 sp=0xc00061dfa0 pc=0xc82a74
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00061dfe8 sp=0xc00061dfe0 pc=0x906e01
created by main.main in goroutine 1
        C:/soft/go-techLog1C-main/main.go:817 +0x11e5

goroutine 1 [chan receive, 11 minutes]:
runtime.gopark(0xc0001672c8?, 0x8ad4a5?, 0x40?, 0x81?, 0x40?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000167260 sp=0xc000167240 pc=0x8d9fee
runtime.chanrecv(0xc00004e7e0, 0xc000167408, 0x1)
        C:/Program Files/Go/src/runtime/chan.go:583 +0x3d0 fp=0xc0001672d8 sp=0xc000167260 pc=0x8a6a50
runtime.chanrecv1(0xc0001676e8?, 0xc0001675c8?)
        C:/Program Files/Go/src/runtime/chan.go:442 +0x12 fp=0xc000167300 sp=0xc0001672d8 pc=0x8a6672
main.main()
        C:/soft/go-techLog1C-main/main.go:821 +0x13a5 fp=0xc000167f40 sp=0xc000167300 pc=0xc828c5
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:267 +0x2b2 fp=0xc000167fe0 sp=0xc000167f40 pc=0x8d9bd2
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000167fe8 sp=0xc000167fe0 pc=0x906e01

goroutine 2 [force gc (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000035fa8 sp=0xc000035f88 pc=0x8d9fee
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:322 +0xb8 fp=0xc000035fe0 sp=0xc000035fa8 pc=0x8d9e78
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000035fe8 sp=0xc000035fe0 pc=0x906e01
created by runtime.init.6 in goroutine 1
        C:/Program Files/Go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000037f78 sp=0xc000037f58 pc=0x8d9fee
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc000037fc8 sp=0xc000037f78 pc=0x8c4a5f
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:200 +0x25 fp=0xc000037fe0 sp=0xc000037fc8 pc=0x8b9d85
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000037fe8 sp=0xc000037fe0 pc=0x906e01
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xf7808c?, 0xe38916?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000045f70 sp=0xc000045f50 pc=0x8d9fee
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x10655e0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000045fa0 sp=0xc000045f70 pc=0x8c22c9
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x8c2879
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:201 +0x25 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x8b9d25
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x906e01
created by runtime.gcenable in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait, 11 minutes]:
runtime.gopark(0x400000?, 0x100039e70?, 0x0?, 0x0?, 0x10ba680?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000039e28 sp=0xc000039e08 pc=0x8d9fee
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:193 +0x107 fp=0xc000039fe0 sp=0xc000039e28 pc=0x8b8e47
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x906e01
created by runtime.createfing in goroutine 1
        C:/Program Files/Go/src/runtime/mfinal.go:163 +0x3d

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x1cbf22a6847c0?, 0x3?, 0x94?, 0x9b?, 0xc000047fb0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000047f50 sp=0xc000047f30 pc=0x8d9fee
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000047fe0 sp=0xc000047f50 pc=0x8bb785
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x906e01
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c

goroutine 13 [running]:
        goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
        C:/soft/go-techLog1C-main/main.go:817 +0x11e5

goroutine 12 [running]:
        goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
        C:/soft/go-techLog1C-main/main.go:817 +0x11e5

goroutine 11 [GC worker (idle), 11 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000175f50 sp=0xc000175f30 pc=0x8d9fee
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000175fe0 sp=0xc000175f50 pc=0x8bb785
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000175fe8 sp=0xc000175fe0 pc=0x906e01
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c

goroutine 19 [GC worker (idle), 3 minutes]:
runtime.gopark(0x10ba680?, 0x1?, 0xa8?, 0x53?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000171f50 sp=0xc000171f30 pc=0x8d9fee
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000171fe0 sp=0xc000171f50 pc=0x8bb785
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000171fe8 sp=0xc000171fe0 pc=0x906e01
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c

goroutine 20 [GC worker (idle), 3 minutes]:
runtime.gopark(0x1cbc930859190?, 0x1?, 0xf4?, 0xa2?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000173f50 sp=0xc000173f30 pc=0x8d9fee
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000173fe0 sp=0xc000173f50 pc=0x8bb785
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000173fe8 sp=0xc000173fe0 pc=0x906e01
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x1cbe7d09c67e4?, 0x3?, 0x90?, 0x42?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc00048ff50 sp=0xc00048ff30 pc=0x8d9fee
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00048ffe0 sp=0xc00048ff50 pc=0x8bb785
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00048ffe8 sp=0xc00048ffe0 pc=0x906e01
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c

goroutine 14 [running]:
        goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
        C:/soft/go-techLog1C-main/main.go:817 +0x11e5

goroutine 16 [running]:
        goroutine running on other thread; stack unavailable
created by main.main in goroutine 1
        C:/soft/go-techLog1C-main/main.go:817 +0x11e5
```

**Comment by NuclearAPK** [comment]
**Общие рекомендации**
1. Проверить что сборка была под архитектуру x64, если нет - пересобрать под х64. Также, операционная система, на которой запускается парсер - должна быть х64
2. Ограничить число потоков (заданий) разбора тех журнала
3. Ограничить события тех журнала - если есть события, которые не особо интересны - их лучше не включать в тех журнал.
4. Настроить сбор метрик  - сколько свободной оперативной памяти и сколько оперативной памяти занимает основной процесс парсера. Исходя из полученных метрик - возможно, прийдется добавить оперативной памяти или использовать подходы, описанные в п.2,3.
